# Generated by Django 4.1.4 on 2022-12-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_orderitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
