# Generated by Django 4.1.4 on 2022-12-25 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_products_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
